### ISSUE TITLE
If n_points in Optimizer.ask() is bigger then 9 ValueError in numpy occurs

### ISSUE THREAD

**Issue by Aschwins** [scikit-optimize/scikit-optimize#1011]
Running [parallel-optimization](https://scikit-optimize.github.io/stable/auto_examples/parallel-optimization.html) example everything runs fine if I use 1-9 query points. But somehow everything above 9 query points hangs. 

To get the same error run the code below. Am I missing something here? My use case requires 48 query points. 

Would love to hear your thoughts!

```
Python 3.8.8 (default, Feb 20 2021, 21:09:14) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> from skopt import Optimizer
>>> from skopt.space import Real
>>> from joblib import Parallel, delayed
>>> # example objective taken from skopt
>>> from skopt.benchmarks import branin
>>> 
>>> optimizer = Optimizer(
...     dimensions=[Real(-5.0, 10.0), Real(0.0, 15.0)],
...     random_state=1,
...     base_estimator='gp'
... )
>>> 
>>> for i in range(1):
...     x = optimizer.ask(n_points=9)  # x is a list of n_points points
...     y = Parallel(n_jobs=4)(delayed(branin)(v) for v in x)  # evaluate points in parallel
...     optimizer.tell(x, y)
... 
          fun: 13.66814170756434
    func_vals: array([ 17.11780242,  25.63679176, 111.24456644, 123.94463659,
        53.4912638 ,  83.95464222,  13.66814171,  14.35518411,
        74.82906435])
       models: []
 random_state: RandomState(MT19937) at 0x7FA3BD074E40
        space: Space([Real(low=-5.0, high=10.0, prior='uniform', transform='normalize'),
       Real(low=0.0, high=15.0, prior='uniform', transform='normalize')])
        specs: {'args': {'self': <skopt.optimizer.optimizer.Optimizer object at 0x7fa3ba89c460>, 'dimensions': [Real(low=-5.0, high=10.0, prior='uniform', transform='identity'), Real(low=0.0, high=15.0, prior='uniform', transform='identity')], 'base_estimator': 'gp', 'n_random_starts': None, 'n_initial_points': 10, 'initial_point_generator': 'random', 'n_jobs': 1, 'acq_func': 'gp_hedge', 'acq_optimizer': 'auto', 'random_state': 1, 'model_queue_size': None, 'acq_func_kwargs': None, 'acq_optimizer_kwargs': None}, 'function': 'Optimizer'}
            x: [-4.635512700781785, 14.054611867944384]
      x_iters: [[5.539674886665384, 0.9247759772133487], [0.6533781426078518, 2.1846509309627606], [2.3976321059971877, 13.33388107457551], [-4.122692211373234, 3.835422267410678], [2.18434866398996, 10.14131246631503], [-0.26536359546881716, 14.474360413114516], [-4.635512700781785, 14.054611867944384], [7.44081018418634, 2.016921234869212], [4.852135388499796, 9.287165289493949]]
>>> # takes ~ 20 sec to get here
>>> print(min(optimizer.yi))  # print the best objective found
13.66814170756434
>>> optimizer = Optimizer(
...     dimensions=[Real(-5.0, 10.0), Real(0.0, 15.0)],
...     random_state=1,
...     base_estimator='gp'
... )
>>> for i in range(1):
...     x = optimizer.ask(n_points=10)  # x is a list of n_points points
...     y = Parallel(n_jobs=4)(delayed(branin)(v) for v in x)  # evaluate points in parallel
...     optimizer.tell(x, y)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/aschilperoort/test/venv/lib/python3.8/site-packages/skopt/optimizer/optimizer.py", line 417, in ask
    opt._tell(x, y_lie)
  File "/home/aschilperoort/test/venv/lib/python3.8/site-packages/skopt/optimizer/optimizer.py", line 536, in _tell
    est.fit(self.space.transform(self.Xi), self.yi)
  File "/home/aschilperoort/test/venv/lib/python3.8/site-packages/skopt/learning/gaussian_process/gpr.py", line 195, in fit
    super(GaussianProcessRegressor, self).fit(X, y)
  File "/home/aschilperoort/test/venv/lib/python3.8/site-packages/sklearn/gaussian_process/_gpr.py", line 235, in fit
    optima = [(self._constrained_optimization(obj_func,
  File "/home/aschilperoort/test/venv/lib/python3.8/site-packages/sklearn/gaussian_process/_gpr.py", line 506, in _constrained_optimization
    opt_res = scipy.optimize.minimize(
  File "/home/aschilperoort/test/venv/lib/python3.8/site-packages/scipy/optimize/_minimize.py", line 619, in minimize
    return _minimize_lbfgsb(fun, x0, args, jac, bounds,
  File "/home/aschilperoort/test/venv/lib/python3.8/site-packages/scipy/optimize/lbfgsb.py", line 306, in _minimize_lbfgsb
    sf = _prepare_scalar_function(fun, x0, jac=jac, args=args, epsilon=eps,
  File "/home/aschilperoort/test/venv/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 261, in _prepare_scalar_function
    sf = ScalarFunction(fun, x0, args, grad, hess,
  File "/home/aschilperoort/test/venv/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 136, in __init__
    self._update_fun()
  File "/home/aschilperoort/test/venv/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 226, in _update_fun
    self._update_fun_impl()
  File "/home/aschilperoort/test/venv/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 133, in update_fun
    self.f = fun_wrapped(self.x)
  File "/home/aschilperoort/test/venv/lib/python3.8/site-packages/scipy/optimize/_differentiable_functions.py", line 130, in fun_wrapped
    return fun(x, *args)
  File "/home/aschilperoort/test/venv/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 74, in __call__
    self._compute_if_needed(x, *args)
  File "/home/aschilperoort/test/venv/lib/python3.8/site-packages/scipy/optimize/optimize.py", line 68, in _compute_if_needed
    fg = self.fun(x, *args)
  File "/home/aschilperoort/test/venv/lib/python3.8/site-packages/sklearn/gaussian_process/_gpr.py", line 227, in obj_func
    lml, grad = self.log_marginal_likelihood(
  File "/home/aschilperoort/test/venv/lib/python3.8/site-packages/sklearn/gaussian_process/_gpr.py", line 481, in log_marginal_likelihood
    alpha = cho_solve((L, True), y_train)  # Line 3
  File "/home/aschilperoort/test/venv/lib/python3.8/site-packages/scipy/linalg/decomp_cholesky.py", line 194, in cho_solve
    b1 = asarray_chkfinite(b)
  File "/home/aschilperoort/test/venv/lib/python3.8/site-packages/numpy/lib/function_base.py", line 488, in asarray_chkfinite
    raise ValueError(
ValueError: array must not contain infs or NaNs
```

**Comment by Aschwins** [comment]
Figured out this error only occurs in the first 2 iterations. After you ran two iterations with optimizer.tell() you can ask for more query points. The following runs fine.

```
import numpy as np
from skopt import Optimizer
from skopt.space import Real
from joblib import Parallel, delayed
# example objective taken from skopt
from skopt.benchmarks import branin

optimizer = Optimizer(
    dimensions=[Real(-5.0, 10.0), Real(0.0, 15.0)],
    random_state=1,
    base_estimator='gp'
)

for i in range(2):
    x = optimizer.ask(n_points=9)  # x is a list of n_points points
    y = Parallel(n_jobs=4)(delayed(branin)(v) for v in x)  # evaluate points in parallel
    optimizer.tell(x, y)

# takes ~ 20 sec to get here
print(min(optimizer.yi))  # print the best objective found

optimizer.ask(n_points=48)
```
