### ISSUE TITLE
Benchmark crashes for gp_minimize with NaN gradients

### ISSUE THREAD

**Issue by betatim** [scikit-optimize/scikit-optimize#266]
Tried running the benchmarks and got:

```
$ python benchmarks/bench_branin.py                                     (skopt)
gp_minimize
0
Traceback (most recent call last):
  File "benchmarks/bench_branin.py", line 23, in <module>
    noise=1e-10)
  File "/Users/thead/git/scikit-optimize/skopt/optimizer/gp.py", line 207, in gp_minimize
    callback=callback)
  File "/Users/thead/git/scikit-optimize/skopt/optimizer/base.py", line 288, in base_minimize
    maxiter=20)
  File "/Users/thead/anaconda/envs/skopt/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 193, in fmin_l_bfgs_b
    **opts)
  File "/Users/thead/anaconda/envs/skopt/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 330, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/Users/thead/anaconda/envs/skopt/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 278, in func_and_grad
    f = fun(x, *args)
  File "/Users/thead/anaconda/envs/skopt/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 289, in function_wrapper
    return function(*(wrapper_args + args))
  File "/Users/thead/anaconda/envs/skopt/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 63, in __call__
    fg = self.fun(x, *args)
  File "/Users/thead/git/scikit-optimize/skopt/acquisition.py", line 16, in gaussian_acquisition_1D
    X, model, y_opt, acq_func, xi, kappa, return_grad=True)
  File "/Users/thead/git/scikit-optimize/skopt/acquisition.py", line 35, in _gaussian_acquisition
    func_and_grad = gaussian_ei(X, model, y_opt, xi, return_grad)
  File "/Users/thead/git/scikit-optimize/skopt/acquisition.py", line 209, in gaussian_ei
    return_std_grad=True)
  File "/Users/thead/git/scikit-optimize/skopt/learning/gaussian_process/gpr.py", line 264, in predict
    X = check_array(X)
  File "/Users/thead/git/scikit-optimize/src/sklearn/sklearn/utils/validation.py", line 406, in check_array
    _assert_all_finite(array)
  File "/Users/thead/git/scikit-optimize/src/sklearn/sklearn/utils/validation.py", line 58, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

**Comment by betatim** [comment]
Same happens at a later stage for `bench_hart6.py`.

**Comment by betatim** [comment]
From a short investigation it seems like the gradients can be `NaN` which upsets `scipy.optimize`

**Comment by MechCoder** [comment]
SciPy version?

**Comment by MechCoder** [comment]
Uggh able to reproduce this in https://github.com/scikit-optimize/scikit-optimize/pull/262
