### ISSUE TITLE
forest_minimize throws exception on NaN/inf somewhere in tree

### ISSUE THREAD

**Issue by scottee** [scikit-optimize/scikit-optimize#301]
I got the exception below while running forest_minimize().  I checked and the objective function never returned a NaN/inf.  The objective function was using precision@6 as a metric.  It had just run 11 iterations.  The 11th iteration returned -0.0920692682266 as its score.  So I'm guessing the exception is due to some number not being convertable to float32??

Any ideas what is wrong and how to work around it?

2017-01-19` 19:31:12,321 INFO __main__: Finished iteration 11, NOT-BEST, metrics:
{'epochs': 41, 'precision@6': 0.092069268, 'learning_rate': 0.0029863437810542567, 'alpha': 1.0590354793387869e-06, 'no_components': 41}
Traceback (most recent call last):
  File "./lightfm_optimize.py", line 86, in <module>
    res_fm = forest_minimize(objective, space, x0=initial_x, n_calls=args.num_iterations, random_state=random_state, verbose=verbose)
  File "/usr/local/lib/python2.7/site-packages/skopt/optimizer/forest.py", line 167, in forest_minimize
    callback=callback, acq_optimizer="sampling")
  File "/usr/local/lib/python2.7/site-packages/skopt/optimizer/base.py", line 262, in base_minimize
    gp.fit(space.transform(Xi), yi)
  File "/usr/local/lib64/python2.7/site-packages/sklearn/ensemble/forest.py", line 247, in fit
    X = check_array(X, accept_sparse="csc", dtype=DTYPE)
  File "/usr/local/lib64/python2.7/site-packages/sklearn/utils/validation.py", line 407, in check_array
    _assert_all_finite(array)
  File "/usr/local/lib64/python2.7/site-packages/sklearn/utils/validation.py", line 58, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

**Comment by scottee** [comment]
Version of scikit-optimize is 0.2 from pypi.

**Comment by betatim** [comment]
From the traceback it looks like the problem is in `X` which is not the value of the objective but the space itself. Could you post how you configured that? Maybe one of the dimensions is too big for a float32?

You could also add a [callback](https://github.com/scikit-optimize/scikit-optimize/blob/master/skopt/callbacks.py) to the optimizer call that stores the fitted model, `X` and `y` for each iteration. Having that callback as part of `skopt` would be a welcome contribution as well I think.

**Comment by scottee** [comment]
Here is the space definition:

`    param_names = ['alpha', 'epochs', 'learning_rate', 'no_components']
    space = [(10**-6, 10**-1, 'log-uniform'),   # alpha (user_alpha and item_alpha)
             (1, 260),                          # epochs
             (10**-4, 1.0, 'log-uniform'),      # learning_rate
             (20, 200),                         # no_components
            ]
`

**Comment by glouppe** [comment]
Before we dig further, does the problem still occur using the development version? (we did quite some changes since 0.2)

**Comment by scottee** [comment]
I'm running this on the dev version now.  In the mean time here are a few other weird hints I noticed.

Hint #1. I collected the X values passed into the objective function (and also the Y values).  Some of the values definitely look like the can't fit in a float32.  When I pass these in as x0 and y0 to forest_minimize() the function doesn't immediately throw the exception, but runs another 10 iterations and then throws the exception.

Hint #2. A lot of the Y values are duplicates of each other.  It seems rather strange to me that with 15M records, I'd get the exact same precision@N value for multiple param configurations.  Of course, this is an issue with the LightFM package doing the training, but I thought it might help.

Hint #3. When I used the json package to print out the values in X and Y, json complained that one of the values can't be converted to JSON.  That value looked just like a float, but something about it is making json croak.  (Unfortunately I've deleted the log, so I don't know which value it was.)  And BTW, pprint doesn't have this problem.

Here are the x0 and y0 values I collected:

    initial_x = [
                    [0, 20, 0.05, 100],
                    [0.0050493637123669851, 60, 0.16338216957521598, 191],
                    [9.5520308870337598e-05, 10, 0.67702914131287817, 178],
                    [0.0011400949411073096, 142, 0.47841002908653185, 157],
                    [8.5408355820235885e-05, 179, 0.93942216355558061, 30],
                    [0.032003157354663921, 260, 0.53705442522804292, 56],
                    [9.6850812942647074e-05, 48, 0.08764303585148385, 116],
                    [8.5016563722117326e-05, 16, 0.05561483704212495, 157],
                    [0.0088491900670198739, 201, 0.0004528910814322813, 164],
                    [0.0088491900670198739, 201, 0.0004528910814322813, 164],
                    [0.073569515750083872, 1, 0.054121552105164714, 48],
                    [1.0590354793387869e-06, 41, 0.0029863437810542567, 41],
                    [1.2729200495235103e-06, 3, 0.0017317720327100126, 44],
                    [0.0068446433483036499, 187, 0.0056314640524548418, 154],
                    [0.00017361969901697941, 36, 0.11678213101355191, 126],
                    [4.0059735533159403e-06, 50, 0.0078268737144327766, 86],
                    [0.045067638849932638, 224, 0.0001058271402859233, 115],
                    [0.001769098654581489, 70, 0.063840233812484715, 87],
                    [5.0507433544562375e-06, 194, 0.032912543326587482, 167],
                    [1.4387047840300756e-05, 193, 0.00012990446928422568, 152],
                    [1.3563646208240071e-05, 11, 0.00021931138961408703, 85],
                    [1.9965248807146357e-05, 138, 0.06681991878544484, 84],
                ]
    initial_y = [
                    -0.089954898,
                    -0.31685087,
                    -0.31685087,
                    -0.31685087,
                    -0.31685087,
                    -0.31685087,
                    -0.31685087,
                    -0.08054807,
                    -0.08054807,
                    -0.08054807,
                    -0.31685087,
                    -0.092069268,
                    -0.08054807,
                    -0.31685087,
                    -0.31685087,
                    -0.097470649,
                    -0.08054807,
                    -0.31685087,
                    -0.087953553,
                    -0.080643423,
                    -0.08054807,
                    -0.089301527,
                ]

**Comment by glouppe** [comment]
Could you share your whole script?

**Comment by scottee** [comment]
I don't know if I can or not.  Let me see if it's got anything proprietary in it...

**Comment by scottee** [comment]
It looks like the dev version failed as well, on iteration 10 again:

2017-01-20 17:42:48,305 INFO __main__: Finished iteration 10, NOT-BEST, metrics:
{'epochs': 26, 'precision@6': 0.08054807, 'learning_rate': 0.065054752945347155, 'no_components': 115, 'alpha': 8.5016563722117326e-05}
Traceback (most recent call last):
  File "./lightfm_optimize.py", line 129, in <module>
    res_fm = forest_minimize(objective, space, x0=initial_x, y0=initial_y, n_calls=args.num_iterations, random_state=random_state, verbose=verbose)
  File "/home/hadoop/scikit-optimize/skopt/optimizer/forest.py", line 171, in forest_minimize
    callback=callback, acq_optimizer="sampling")
  File "/home/hadoop/scikit-optimize/skopt/optimizer/base.py", line 241, in base_minimize
    optimizer.tell(next_x, next_y, fit=fit_model)
  File "/home/hadoop/scikit-optimize/skopt/optimizer/optimizer.py", line 234, in tell
    est.fit(self.space.transform(self.Xi), self.yi)
  File "/usr/local/lib64/python2.7/site-packages/sklearn/ensemble/forest.py", line 247, in fit
    X = check_array(X, accept_sparse="csc", dtype=DTYPE)
  File "/usr/local/lib64/python2.7/site-packages/sklearn/utils/validation.py", line 407, in check_array
    _assert_all_finite(array)
  File "/usr/local/lib64/python2.7/site-packages/sklearn/utils/validation.py", line 58, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

**Comment by scottee** [comment]
I can share the script, but it won't be runnable, since the data is proprietary.  If that will be enough to help you, let me know and I'll share it.

**Comment by scottee** [comment]
Here's a stripped down script that illustrates the problem.  It's runnable.  The exception seems to happen soon after n_random_starts is satisfied (so I passed in 0 for it).

[skopt_problem.py.zip](https://github.com/scikit-optimize/scikit-optimize/files/720295/skopt_problem.py.zip)

**Comment by scottee** [comment]
Found the problem. There is a np.log10() call on a space parameter (alpha) that can have a zero value, which causes -inf to end up in the array going into the tree.  I don't know what the fix is; you guys are the experts there.  (Use a small epsilon instead of zero?  Or do whatever hyperopt does?)  

And now that I think of it, 0 is out of the alpha space range, so some range checking on the space could have avoided the problem also.

My work around is to use a small epsilon instead of zero for initial alpha.

Attached is a debugging session that illustrates the problem.

[debug.out.zip](https://github.com/scikit-optimize/scikit-optimize/files/720323/debug.out.zip)

**Comment by glouppe** [comment]
Thanks, good catch. Indeed, you shouldnt specify initial points outside of the bounds you provide and  you should make sure log10(x) is define over the interval you chose. 

That being said, this calls for a better warning from our side to make this issue is easy to debug by the user.

**Comment by betatim** [comment]
Should check when `Optimizer.tell()` is called that the point is within the limits and each `Dimension` class checks if the range makes sense.
