### ISSUE TITLE
GradientBoostingQuantileRegressor: non-broadcastable output operand with shape (3,) doesn't match the broadcast shape (3,3)

### ISSUE THREAD

**Issue by iaroslav-ai** [scikit-optimize/scikit-optimize#348]
When I run the following code:
```
from skopt import Optimizer
from skopt.learning import GradientBoostingQuantileRegressor
from skopt.space import Real

opt = Optimizer([Real(-1,1)],GradientBoostingQuantileRegressor(),acq_optimizer='sampling')

def obj(x):
    return sum(x)

for i in range(128):
    x = opt.ask()
    y = obj(x)
    opt.tell(x, y)
```
it throws an exception:
```
/usr/bin/python2.7 /home/iaroslav/scikit-optimize/benchmarks/min_gbrt.py
Traceback (most recent call last):
  File "/home/iaroslav/scikit-optimize/benchmarks/min_gbrt.py", line 13, in <module>
    opt.tell(x, y)
  File "/home/iaroslav/scikit-optimize/skopt/optimizer/optimizer.py", line 271, in tell
    self.gains_ -= est.predict(np.vstack(self.next_xs_))
ValueError: non-broadcastable output operand with shape (3,) doesn't match the broadcast shape (3,3)

Process finished with exit code 1
```
If I try to run this with other surrogates, I do not experience this exception. Looks like a bug. 
The code was run on python 2.7.

**Comment by iaroslav-ai** [comment]
Setting `acq_func='EI'` in Optimizer solves the issue. It seems that default `acq_func="gp_hedge"` does not work well with `GradientBoostingQuantileRegressor`.

**Comment by iaroslav-ai** [comment]
Appears to be solved now. Closing.
