### ISSUE TITLE
Compatibility of the ask and tell API with acquisition function EIps

### ISSUE THREAD

**Issue by chschroeder** [scikit-optimize/scikit-optimize#560]
It seems i cannot use acquisition functions that incorporate the runtime (EIps, PIps) when using the ask and tell API.

My objective function returns a tuple of (result, time), this part should be correct imho. The error is thrown during the lying step of the optimizer.

I get the following error:
```
[shortened]
File "/usr/local/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 339, in ask
    opt.tell(x, y_lie)  # lie to the optimizer
  File "/usr/local/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 417, in tell
    raise TypeError("expected y to be (func_val, t)")
TypeError: expected y to be (func_val, t)
```

Are the ask and tell api and EIps not supposed to work together, or am i missing something?
(Version: v0.4)

**Comment by betatim** [comment]
Can't think of a reason why they should not work together, so this is most likely a bug. Would you be interested in proposing a fix? (We can work together to find the right thing to do if you want to).

**Comment by chschroeder** [comment]
Sure. Howevery, after constructing a minimal reproducible example i think the error must be on my side.

```
"""
Based on examples/ask-and-tell.ipynb
"""
import numpy as np
from skopt import Optimizer

def objective(x):
    seconds = 1
    return np.sin(5 * x[0]) * (1 - np.tanh(x[0] ** 2)), seconds

opt = Optimizer([(-2.0, 2.0)], 'ET', acq_func='EIps', acq_optimizer='sampling')

for i in range(9):
    next_x = opt.ask()
    f_val = objective(next_x)
    opt.tell(next_x, f_val)
```

Thanks for your fast response anyway! I will recheck the rest of my code and update this issue if the problem persists.

**Comment by chschroeder** [comment]
I re-examined, everything is working fine :) The mistake was in another part of my code.

**Comment by chschroeder** [comment]
Closed this too soon. If i pass `n_points=5` to the ask method i can reproduce the error.

```
"""
Minimal reproducible example for #560
(https://github.com/scikit-optimize/scikit-optimize/issues/560)
"""
import numpy as np

from skopt import Optimizer

def objective(x):
    seconds = 1
    return np.sin(5 * x[0]) * (1 - np.tanh(x[0] ** 2)), seconds

opt = Optimizer([(-2.0, 2.0)], 'ET', acq_func='EIps', acq_optimizer='sampling')

for i in range(9):
    next_x = opt.ask(n_points=5)
    f_val = objective(next_x)
    opt.tell(next_x, f_val)
```

If i read the docs correctly this should work. Correct me if i'm wrong.
This seems like a rather easy task and i would love to contribute.
I will look into it as soon as my schedule permits.

**Comment by chschroeder** [comment]
@betatim It seems that during the lying step the computation time is not considered at all (and thus crashes for acquisition functions containing "ps").

This probably means that the part where the lying is done needs to be adapted. The [paper](https://hal.archives-ouvertes.fr/hal-00732512/document), which is linked in the docstrings, does not seem to consider lying on computation times. I need to think about this, but my first intuition would be to simply keep track of the runtime values in the same way as it is done for the objective values (yi). And then treat them exactly the same as the objective values for the min / mean / max cl stratgies.

Still, i am not sure if this just fixes the code, or is a desirable solution.

**Comment by kejiashi** [comment]
Your objective function simply does not support multiple points. Check again!

**Comment by chschroeder** [comment]
You are right on that, however this is not the issue that troubles me.

The error is raised during the ask call. My real code shows the same behavior (the objective there was fine).

```
Traceback (most recent call last):
  File "skopt_eips_ask_tell.py", line 16, in <module>
    next_x = opt.ask(n_points=5)
  File "/usr/local/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 341, in ask
    opt.tell(x, y_lie)  # lie to the optimizer
  File "/usr/local/lib/python3.6/site-packages/skopt/optimizer/optimizer.py", line 419, in tell
    raise TypeError("expected y to be (func_val, t)")
TypeError: expected y to be (func_val, t)
```

**Comment by chschroeder** [comment]
Currently working on a solution. So far i have identified two problems. I will keep you posted.

**Comment by betatim** [comment]
Thanks! Feel free to open a PR and mark it as "[WIP] <your title here>". Seeing it develop tends to help people review it more quickly and we can discuss directly on the code.
