### ISSUE TITLE
Visualization of results using categorical parameters

### ISSUE THREAD

**Issue by christianblust** [scikit-optimize/scikit-optimize#660]
Hi, 
I'm trying to optimize a `RandomForestClassifier `including [criterion ](url)as a parameter (`gini `vs. `entropy`). Are the functions `plot_evaluations `and `plot_convergence `intended for optimization including categorical parameters? `plots.plot_objective(res_rf)` results in the following error.

```
Traceback (most recent call last):
  File "C:/Users/chris/PycharmProjects/FormationDetection/TestHyperOpt.py", line 176, in <module>
    plots.plot_objective(res_rf)
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\skopt\plots.py", line 343, in plot_objective
    rvs_transformed, n_points)
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\skopt\plots.py", line 245, in partial_dependence
    yi = np.linspace(bounds[0], bounds[1], n_points)
  File "C:\Users\chris\PycharmProjects\FormationDetection\venv\lib\site-packages\numpy\core\function_base.py", line 108, in linspace
    start = asanyarray(start) * 1.0
TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')
```
However `plot_evaluations(res_rf )`creates a figure but it doesn't seem to be correct.

My code:
```
space= [Integer(1, 20, name='max_depth'),
        Integer(2, 100, name='min_samples_split'),
        Integer(5, 30, name='min_samples_leaf'),
        Integer(100,1000, name='n_estimators'),
        Integer(1, n_features, name='max_features'),
        Categorical(['gini', 'entropy'], name='criterion')
        ]

def objective(params):
    max_depth = params[0]
    min_samples_split = params[1]
    min_samples_leaf = params[2]
    n_estimators = params[3]
    max_features = params[4]
    criterion = params[5]

    rf = RandomForestClassifier(random_state=42, max_depth=max_depth, min_samples_split=min_samples_split,
                                min_samples_leaf=min_samples_leaf, n_estimators=n_estimators, max_features=max_features, criterion=criterion)
    return -np.mean(cross_val_score(rf, x_train, y_train, cv=skf, scoring="accuracy"))

counter = 0
def onstep(res):
    global counter
    list = res.x
    print('current iteration: ', counter, ' - Score ', res.fun, ' - Args: ', list[0], list[1], list[2], list[3], list[4], list[5])
    counter = counter+1

if __name__ == '__main__':
    res_rf = gp_minimize(objective, space, n_calls=10, random_state=42, callback=onstep)
    print('debug')
    plots.plot_evaluations(res_rf, bins=10)
    #plots.plot_objective(res_rf)
    #plots.plot_convergence(res_rf)
    plt.show()
```

**Comment by christianblust** [comment]
![figure_1](https://user-images.githubusercontent.com/27559141/38948915-282558fa-4341-11e8-87a4-c7c362a05651.png)

**Comment by jkleint** [comment]
Unfortunately, you're right: the visualizations currently do not support categorical parameters.  There is an issue for it:  #396

**Comment by christianblust** [comment]
Is it possible to do the parameter tuning including categorical parameters but to exclude them in the visualization? (But still margin them out)

**Comment by bionicles** [comment]
this should definitely be handled automatically so every user doesn't have to reinvent the wheel, especially since there are no docs on how to remove these dimensions or remove them from results
