### ISSUE TITLE
ValueError: Dimension has to be a list or tuple

### ISSUE THREAD

**Issue by Liquidten** [scikit-optimize/scikit-optimize#731]
Traceback (most recent call last):

  File "<ipython-input-91-3ab6d73131bd>", line 1, in <module>
    runfile('/Users/sameepshah/Desktop/Data/Practice/skoptHyperParm.py', wdir='/Users/sameepshah/Desktop/Data/Practice')

  File "/Users/sameepshah/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/Users/sameepshah/anaconda3/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/sameepshah/Desktop/Data/Practice/skoptHyperParm.py", line 315, in <module>
    x0=default_parameters)

  File "/Users/sameepshah/anaconda3/lib/python3.6/site-packages/skopt/optimizer/gp.py", line 214, in gp_minimize
    space = normalize_dimensions(dimensions)

  File "/Users/sameepshah/anaconda3/lib/python3.6/site-packages/skopt/utils.py", line 472, in normalize_dimensions
    space = Space(dimensions)

  File "/Users/sameepshah/anaconda3/lib/python3.6/site-packages/skopt/space/space.py", line 570, in __init__
    self.dimensions = [check_dimension(dim) for dim in dimensions]

  File "/Users/sameepshah/anaconda3/lib/python3.6/site-packages/skopt/space/space.py", line 570, in <listcomp>
    self.dimensions = [check_dimension(dim) for dim in dimensions]

  File "/Users/sameepshah/anaconda3/lib/python3.6/site-packages/skopt/space/space.py", line 70, in check_dimension
    raise ValueError("Dimension has to be a list or tuple.")

ValueError: Dimension has to be a list or tuple.

Hi guys I was trying to run your posted hyperparameter tuning model. I am getting this error help much appreciated.

Thanks

**Comment by dingjinjun** [comment]
Same error.  skopt optimizer really sucks!

**Comment by bertvan** [comment]
You probably are using an invalid form for the search_spaces parameter.
See here: https://scikit-optimize.github.io/#skopt.BayesSearchCV -> Parameters -> search_spaces

**Comment by dingjinjun** [comment]
Never mind, I figured it out yesterday.

**Comment by iaroslav-ai** [comment]
Thanks @dingjinjun , @bertvan !

**Comment by Sherlock1118** [comment]
can you tell us how to figure this error out？ @jim0607

**Comment by jim0607** [comment]
Ahhh.  It's been a long time, but I kinda remember it's some version issue.  Hope it helps! @Sherlock1118
