### ISSUE TITLE
Doctest failure

### ISSUE THREAD

**Issue by PureTryOut** [scikit-optimize/scikit-optimize#925]
Using scikit-optimize version 0.7.4, the doctests fail:

```
================================================ test session starts ================================================
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /home/bart/Documents/Git/alpine/aports/community/py3-scikit-optimize/src/scikit-optimize-0.7.4, inifile: setup.cfg
collected 6 items                                                                                                   

skopt/callbacks.py .                                                                                          [ 16%]
skopt/searchcv.py F                                                                                           [ 33%]
skopt/utils.py ....                                                                                           [100%]

===================================================== FAILURES ======================================================
______________________________________ [doctest] skopt.searchcv.BayesSearchCV _______________________________________
180     ...         'gamma': Real(1e-6, 1e+1, prior='log-uniform'),
181     ...         'degree': Integer(1,8),
182     ...         'kernel': Categorical(['linear', 'poly', 'rbf']),
183     ...     },
184     ...     n_iter=32,
185     ...     random_state=0
186     ... )
187     >>>
188     >>> # executes bayesian optimization
189     >>> _ = opt.fit(X_train, y_train)
UNEXPECTED EXCEPTION: TypeError('object.__init__() takes exactly one argument (the instance to initialize)')
Traceback (most recent call last):
  File "/usr/lib/python3.8/doctest.py", line 1336, in __run
    exec(compile(example.source, filename, "single",
  File "<doctest skopt.searchcv.BayesSearchCV[8]>", line 1, in <module>
  File "/home/bart/Documents/Git/alpine/aports/community/py3-scikit-optimize/src/scikit-optimize-0.7.4/skopt/searchcv.py", line 678, in fit
    optim_result = self._step(
  File "/home/bart/Documents/Git/alpine/aports/community/py3-scikit-optimize/src/scikit-optimize-0.7.4/skopt/searchcv.py", line 566, in _step
    self._fit(X, y, groups, params_dict)
  File "/home/bart/Documents/Git/alpine/aports/community/py3-scikit-optimize/src/scikit-optimize-0.7.4/skopt/searchcv.py", line 479, in _fit
    param_results["param_%s" % name][cand_i] = value
  File "/usr/lib/python3.8/site-packages/sklearn/utils/deprecation.py", line 68, in wrapped
    return init(*args, **kwargs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
/home/bart/Documents/Git/alpine/aports/community/py3-scikit-optimize/src/scikit-optimize-0.7.4/skopt/searchcv.py:189: UnexpectedException
```

**Comment by PureTryOut** [comment]
This seems to have been fixed with 0.8.0, closing.
