### ISSUE TITLE
Python-BaseException raised when trying the BayesSearchCV example

### ISSUE THREAD

**Issue by heatherwilson282** [scikit-optimize/scikit-optimize#928]
I am trying to understand how to use the BayesSearchCV, and tried the example provided, but a Python-BaseException was raised. I've used the exact code that was provided in the example.
 
Here is the error message:
 
Connected to pydev debugger (build 202.6397.94)
/Users/heather.wilson/Code/code_lab/venv/lib/python3.7/site-packages/sklearn/utils/validation.py:71: FutureWarning: Pass return_X_y=True as keyword args. From version 0.25 passing these as positional arguments will result in an error
  FutureWarning)
/Users/heather.wilson/Code/code_lab/venv/lib/python3.7/site-packages/sklearn/utils/deprecation.py:67: FutureWarning: Class MaskedArray is deprecated; MaskedArray is deprecated in version 0.23 and will be removed in version 0.25. Use numpy.ma.MaskedArray instead.
  warnings.warn(msg, category=FutureWarning)
Traceback (most recent call last):
  File "/Users/heather.wilson/Library/Application Support/JetBrains/IntelliJIdea2020.2/plugins/python/helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/heather.wilson/Library/Application Support/JetBrains/IntelliJIdea2020.2/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/heather.wilson/Code/code_lab/__main__.py", line 27, in <module>
    main()
  File "/Users/heather.wilson/Code/code_lab/__main__.py", line 22, in main
    _ = opt.fit(X_train, y_train)
  File "/Users/heather.wilson/Code/code_lab/venv/lib/python3.7/site-packages/skopt/searchcv.py", line 680, in fit
    groups=groups, n_points=n_points_adjusted
  File "/Users/heather.wilson/Code/code_lab/venv/lib/python3.7/site-packages/skopt/searchcv.py", line 566, in _step
    self._fit(X, y, groups, params_dict)
  File "/Users/heather.wilson/Code/code_lab/venv/lib/python3.7/site-packages/skopt/searchcv.py", line 479, in _fit
    param_results["param_%s" % name][cand_i] = value
  File "/Users/heather.wilson/Code/code_lab/venv/lib/python3.7/site-packages/sklearn/utils/deprecation.py", line 68, in wrapped
    return init(*args, **kwargs)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
python-BaseException

**Comment by Yard1** [comment]
It seems to be an issue of scikit-optimize not being updated for the newest scikit-learn version.
