### ISSUE TITLE
ValueError: All integer values shouldbe greater than 0.000000

### ISSUE THREAD

**Issue by catapiqui** [scikit-optimize/scikit-optimize#957]
Please can anyone give me a hand with this? Pops up when I run xgboost through BayesSearchCv

skop v 0.8.1 and numpy 1.16.2
python 3.7.3
OS: windows 10

```
Traceback (most recent call last):

  File "<ipython-input-189-dc299c53649b>", line 1, in <module>
    result = bayes_cv_tuner.fit(X, y, callback=print_status, groups=data_nobands2.AGREEMENT_NUMBER2)

  File "C:\Users\CatKa\Anaconda3\lib\site-packages\skopt\searchcv.py", line 694, in fit
    groups=groups, n_points=n_points_adjusted

  File "C:\Users\CatKa\Anaconda3\lib\site-packages\skopt\searchcv.py", line 565, in _step
    params = optimizer.ask(n_points=n_points)

  File "C:\Users\CatKa\Anaconda3\lib\site-packages\skopt\optimizer\optimizer.py", line 417, in ask
    opt._tell(x, y_lie)

  File "C:\Users\CatKa\Anaconda3\lib\site-packages\skopt\optimizer\optimizer.py", line 553, in _tell
    n_samples=self.n_points, random_state=self.rng))

  File "C:\Users\CatKa\Anaconda3\lib\site-packages\skopt\space\space.py", line 963, in transform
    columns[j] = self.dimensions[j].transform(columns[j])

  File "C:\Users\CatKa\Anaconda3\lib\site-packages\skopt\space\space.py", line 162, in transform
    return self.transformer.transform(X)

  File "C:\Users\CatKa\Anaconda3\lib\site-packages\skopt\space\transformers.py", line 304, in transform
    X = transformer.transform(X)

  File "C:\Users\CatKa\Anaconda3\lib\site-packages\skopt\space\transformers.py", line 251, in transform
    "be greater than %f" % self.low)

ValueError: All integer values shouldbe greater than 0.000000
```

**Comment by davidfstein** [comment]
Having the same issue. I've tried increasing the lower limits of my sample space but then the error just increases the threshold i.e. "ValueError: All integer values shouldbe greater than 0.000001" and ValueError: All integer values shouldbe greater than 0.000010", etc.

**Comment by jerryji1993** [comment]
Having this same issue here.

**Comment by ThomasWolf0701** [comment]
Also have the same issue.

**Comment by ThomasWolf0701** [comment]
With lightgbm it works fine:

  
 # Classifier
bayes_cv_tuner = skopt.BayesSearchCV(
    estimator = lgb.LGBMRegressor(
       # objective='binary',
        metric='rmse',
        n_jobs=8,
        verbose=0
    ),
    search_spaces = {
        'learning_rate': (0.01, 1.0, 'log-uniform'),
        'num_leaves': (1, 100),      
        'max_depth': (0, 50),
        'min_child_samples': (0, 50),
        'max_bin': (100, 1000),
        'subsample': (0.01, 1.0, 'uniform'),
        'subsample_freq': (0, 10),
        'colsample_bytree': (0.01, 1.0, 'uniform'),
        'min_child_weight': (0, 10),
        'subsample_for_bin': (100000, 500000),
        'reg_lambda': (1e-9, 1000, 'log-uniform'),
        'reg_alpha': (1e-9, 1.0, 'log-uniform'),
        'scale_pos_weight': (1e-6, 500, 'log-uniform'),
        'n_estimators': (50, 100),
    },    
    scoring = 'roc_auc',
    cv = KFold(
        n_splits=3,
        shuffle=True,
        random_state=42
    ),
    n_jobs = 1,
    n_iter = 3,   
    verbose = 0,
    refit = True,
    random_state = 42
)

# Fit the model
result = bayes_cv_tuner.fit(featureMatrix, values) #callback=status_print)

**Comment by masgra** [comment]
change your search space formating, e.g. instead of 
`'learning_rate': (0.01, 1.0, 'log-uniform'), `

use 
`from skopt.space import Real 
'learning_rate': Real(low=0.01, high=10,  prior='log-uniform'), `

This worked for me at least.
