### ISSUE TITLE
TypeError: can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by davidfstein** [scikit-optimize/scikit-optimize#985]
I'm having trouble using BayesCVSearch with a Keras Neural Net. I keep receiving the error in the title.

code:
```
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn import metrics
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.callbacks import ModelCheckpoint
from keras.models import load_model
from keras.utils import to_categorical
from keras.wrappers.scikit_learn import KerasClassifier
from keras.callbacks import LearningRateScheduler
import tensorflow as tf
from sklearn.model_selection import StratifiedKFold
from skopt import BayesSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from skopt.space import Real, Categorical, Integer
from notebooks import preprocess as prepro
import math

def status_print(optim_result):
    """Status callback durring bayesian hyperparameter search"""

    # Get all the models tested so far in DataFrame format
    all_models = pd.DataFrame(bayes_cv_tuner.cv_results_)

    # Get current parameters and the best parameters
    best_params = pd.Series(bayes_cv_tuner.best_params_)
    print('Model #{}\nBest F1: {}\nBest params: {}\n'.format(
        len(all_models),
        np.round(bayes_cv_tuner.best_score_, 4),
        bayes_cv_tuner.best_params_
    ))

    # Save all model results
    clf_name = bayes_cv_tuner.estimator.__class__.__name__
    all_models.to_csv(clf_name+"_cv_results.csv")

def create_model(shape, 
                activation1='elu',
                dropout1=0.3,
                dropout2=0.3,
                optimizer=None, 
                lr = .1):
    if not optimizer:
         optimizer = keras.optimizers.Adamax(learning_rate=lr, name="Adamax")
    # define model
    model = Sequential()
    model.add(Dropout(dropout1, input_shape=(shape,)))
    model.add(Dense(256, activation=activation1))
    model.add(Dropout(dropout2))
    model.add(Dense(1, activation='sigmoid'))
    # compile model
    model.compile(loss='binary_crossentropy',
              optimizer=optimizer,
              metrics=['accuracy'])
    return model

if __name__ == '__main__':
    X_train, y_train, _ = prepro.scipre_no_split('./split_datasets/goflof_string_train.csv', select_features='boruta')
    params_dict = {'dropout1': Real(0.01, 1.0, 'log-uniform'),
                   'dropout2': Real(0.01, 1.0, 'log-uniform'),
                   'activation1': Categorical(['elu', 'relu', 'selu']),
                   'lr': Real(1e-5, 1, prior='log-uniform')
    }
    model = create_model(shape=X_train.shape[1])
    bayes_cv_tuner = BayesSearchCV(
        estimator = KerasClassifier(model, epochs=200, batch_size=32),
        scoring = 'average_precision',
        fit_params={'class_weight': {0:1, 1:10}},
        search_spaces = params_dict,
        cv = StratifiedKFold(
            n_splits=3,
            shuffle=True,
            random_state=42
        ),
            n_jobs = 80,
            n_points = 3,
            n_iter = 200,
            verbose = 0,
            refit = False,
            random_state = 1
    )
    result = bayes_cv_tuner.fit(X_train, y_train, callback=status_print)
```

traceback:
```
Traceback (most recent call last):
  File "scripts/neural_search.py", line 89, in <module>
    result = bayes_cv_tuner.fit(X_train, y_train, callback=status_print)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/skopt/searchcv.py", line 694, in fit
    groups=groups, n_points=n_points_adjusted
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/skopt/searchcv.py", line 579, in _step
    self._fit(X, y, groups, params_dict)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/skopt/searchcv.py", line 406, in _fit
    base_estimator = clone(self.estimator)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/sklearn/base.py", line 87, in clone
    new_object_params[name] = clone(param, safe=False)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/site-packages/sklearn/base.py", line 71, in clone
    return copy.deepcopy(estimator)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 216, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 216, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 281, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 241, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/itan_lab/david/.conda/envs/goflof/lib/python3.7/copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle _thread.RLock objects
```

**Comment by davidfstein** [comment]
Maybe someone can provide a successful example of tuning a Kera Neural Net with BayesSearchCV

**Comment by kernc** [comment]
Try this:
https://stackoverflow.com/questions/48303166/keras-typeerror-cant-pickle-thread-lock-objects-with-kerasclassifier/48303535#48303535

`model` iteself can't be pickled so instead you pass in and pickle a mere function that returns it.

**Comment by davidfstein** [comment]
That works
